# Generated by Django 4.2.14 on 2025-01-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="character_name",
            new_name="name_text",
        ),
        migrations.AddField(
            model_name="character",
            name="strength_int",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
