# Generated by Django 4.2.14 on 2025-01-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_character_name_character_name_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="strength_int",
            field=models.IntegerField(default=0),
        ),
    ]
