services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./backend
        target: /app